### ISSUE TITLE
Store last change IP time

### ISSUE THREAD

**Issue by badrogger** [skalenetwork/skale-manager#1013]
To gracefully handle ip change automatically off-chain components should understand when last change IP transaction was sent. The purspose of this task is to store timestamp for the last chaingeIP transaction on skale-manager.

**Comment by DmytroNazarenko** [comment]
skale-manager: 1.10.0-beta.0

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
admin: `2.6.0-beta.0`
skale-manager: `1.10.0-beta.0`

There is call `getLastChangeIpTime` on Nodes contract. 

```
[ getLastChangeIpTime method response ]

[

  timestamp (uint256) : 1707329568

]
```
