### ISSUE TITLE
Additional events after smart contract actions

### ISSUE THREAD

**Issue by lukanus** [skalenetwork/skale-manager#498]
Hey! 

During the work on indexer, we've discovered that it is impossible to get the information about changes of some structures in smart contracts. Changes are made implicitly and it would be great to have this information on update, so we can take current state of those. 

The ones we were able to get so far: 

### Validator 
* MDA [link](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/delegation/ValidatorService.sol#L287)
* Name [link](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/delegation/ValidatorService.sol#L297)
* Description [link](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/delegation/ValidatorService.sol#L307)
* Active/Inactive [link](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/delegation/ValidatorService.sol#L321)
* Requested Addresses  [link](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/delegation/ValidatorService.sol#L217)
 
We probably don't need to know what happened since we'll take the newest version of structure from smart contract anyway, but it would be great to have `event ValidatorChanged(uint validatorId);`  emitted after every Validator change. 

### Nodes 
* State (active) [link](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/Nodes.sol#L807)
* State (in maintenance) [link](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/Nodes.sol#L815)
* State (leaving) [link](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/Nodes.sol#L839)
* State (left) [link](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/Nodes.sol#L823)

Similarly to Validator just information about the node index would be enough. `event NodeStateChanged(uint nodeIndex);`

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-3785)

**Comment by gannakulikova** [comment]
@lukanus  thank you! We will plan this further
