### ISSUE TITLE
Node exit is failing after deleting sChain by root

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/skale-manager#734]
### Information
Node exit is failing with revert `The schain does not exist` after removal of the sChain with previously failed DKG.

### Steps to reproduce the behavior
1. Create 4 nodes
1. Create 4-nodes sChain 
1. Run DKG
1. Create one more node
1. Do `nodeExit` for one of the nodes
1. Create one more node
1. Fail DKG, send `complaint` to the bad node
1. Complete DKG for the new set of nodes
1. Run `deleteSchainByRoot` for this chain
1. Run `nodeExit` for all nodes

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-4833)

**Comment by DimaStebaev** [comment]
It was fixed in https://github.com/skalenetwork/skale-manager/pull/714.
