### ISSUE TITLE
Function duplication in SchainsInternal

### ISSUE THREAD

**Issue by DimaStebaev** [skalenetwork/skale-manager#847]
`SchainsInternal` has two functions:

- `getSchainHashesForNode`
- `getSchainIdsForNode`

that are identical.
One of them must be removed.

Note: both functions work incorrectly after node rotation and probably must be removed in favor of `getActiveSchains`.

**Comment by DimaStebaev** [comment]
Now current behavior of the `getSchainHashesForNode` is used in `skale-admin` to allocate ports.
In this function after SKALE chain removing deleted chain hash continues to be returned as `0x0`.

**Comment by PolinaKiporenko** [comment]
1.9.3-beta.1

**Comment by EvgeniyZZ** [comment]
On of removed is ``getSchainIdsForNode```
SM 2.1 T12412
