### ISSUE TITLE
Calculate rewards up to 10 years by 1 "withdrawBounty"

### ISSUE THREAD

**Issue by payvint** [skalenetwork/skale-manager#925]
## Current problem
There is a limit in Distributor contract that you can claim bounty for 12 months max. And if you delegated 25 months ago, and want to claim rewards - you need to call withdrawBounty 3 times(12 + 12 + 1). This limit was introduce by high gas consumption of function "withdrawBounty" - by 12 months to would cost 810K of gas. And right now on all platforms (Activate, Delegation Portal, Skale Analytics) claimable reward shows only by 12 months which make clients confused of small amount. Results provided by call "getAndUpdateEarnedBountyAmountOf".

## Solution
It would be good to increase a limit by 10 years(120 months) or higher, gas consumption would be 8M of gas(which still fit in block gas limit 30M). It would show correct amount of claimable rewards for the 10 year period.
10 year - 8M gas
30 year - 24M gas

**Comment by payvint** [comment]
I would say increase up to 30 year - would make more sense till if fits in the block gas limit

**Comment by DimaStebaev** [comment]
The fix is a matter of changing a 1 constant in a 1 contract.

**Comment by yatsunastya** [comment]
Version: `1.12.0-beta.2`

For validators earned fees calculation is still 12 months. 
[Code reference](https://github.com/skalenetwork/skale-manager/blob/develop/contracts/delegation/Distributor.sol#L269)

**Comment by yatsunastya** [comment]
Checked bounty calculation for a holder. 
Version: `1.12.0-beta.2`

`withdrawBounty` [transaction](https://eth.blockscout.com/tx/0x9b7dd84d10611459695bbc609eadc23e8e79eb7bff05f966fc7b9034e8a55f18) on `1.11.0` version. There are bounties for ~ 2.5 years, but it was withdrawn for 12 months. 
![Image](https://github.com/user-attachments/assets/2f3c56d5-c557-4f1f-9efd-50177b2f5eea)

`withdrawBounty` [transaction](https://eth-holesky.blockscout.com/tx/0xa702ee486b436f390f942e0fde58136f9ba171334c948b8750fd5809ad696d85) on `1.12.0-beta.2` version. There are bounties for ~ 3.5 years and it was withdrawn for ~ 42 months.
<img width="588" alt="Знімок екрана 2024-09-27 о 13 27 38" src="https://github.com/user-attachments/assets/2f847853-e4b5-4766-ae7e-ed282b672e6a">

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [1.12.0-beta.4](https://github.com/skalenetwork/skale-manager/releases/tag/1.12.0-beta.4)

[`withdrawFee`](https://eth-holesky.blockscout.com/tx/0x41afe1b05ce1ef2a45933d67b87844569c2f4e2c2539cc0d605a8d2d692ac3dc) transaction. There are fees for ~ 42 months.
